// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: codeday/squareassault/protobuf/main.proto

package codeday.squareassault.protobuf;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface IdentifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Identify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code tutorial.Identify}
   */
  public static final class Identify extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.Identify)
      IdentifyOrBuilder {
    // Use Identify.newBuilder() to construct.
    private Identify(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Identify(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Identify defaultInstance;
    public static Identify getDefaultInstance() {
      return defaultInstance;
    }

    public Identify getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Identify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_Identify_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_Identify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codeday.squareassault.protobuf.Messages.Identify.class, codeday.squareassault.protobuf.Messages.Identify.Builder.class);
    }

    public static com.google.protobuf.Parser<Identify> PARSER =
        new com.google.protobuf.AbstractParser<Identify>() {
      public Identify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Identify(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Identify> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.Identify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(codeday.squareassault.protobuf.Messages.Identify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Identify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Identify)
        codeday.squareassault.protobuf.Messages.IdentifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_Identify_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_Identify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codeday.squareassault.protobuf.Messages.Identify.class, codeday.squareassault.protobuf.Messages.Identify.Builder.class);
      }

      // Construct using codeday.squareassault.protobuf.Messages.Identify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_Identify_descriptor;
      }

      public codeday.squareassault.protobuf.Messages.Identify getDefaultInstanceForType() {
        return codeday.squareassault.protobuf.Messages.Identify.getDefaultInstance();
      }

      public codeday.squareassault.protobuf.Messages.Identify build() {
        codeday.squareassault.protobuf.Messages.Identify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public codeday.squareassault.protobuf.Messages.Identify buildPartial() {
        codeday.squareassault.protobuf.Messages.Identify result = new codeday.squareassault.protobuf.Messages.Identify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codeday.squareassault.protobuf.Messages.Identify) {
          return mergeFrom((codeday.squareassault.protobuf.Messages.Identify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codeday.squareassault.protobuf.Messages.Identify other) {
        if (other == codeday.squareassault.protobuf.Messages.Identify.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        codeday.squareassault.protobuf.Messages.Identify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (codeday.squareassault.protobuf.Messages.Identify) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Identify)
    }

    static {
      defaultInstance = new Identify(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Identify)
  }

  public interface LineMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.LineMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code tutorial.LineMessage}
   */
  public static final class LineMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.LineMessage)
      LineMessageOrBuilder {
    // Use LineMessage.newBuilder() to construct.
    private LineMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LineMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LineMessage defaultInstance;
    public static LineMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LineMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LineMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_LineMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_LineMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codeday.squareassault.protobuf.Messages.LineMessage.class, codeday.squareassault.protobuf.Messages.LineMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LineMessage> PARSER =
        new com.google.protobuf.AbstractParser<LineMessage>() {
      public LineMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LineMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LineMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.LineMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(codeday.squareassault.protobuf.Messages.LineMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.LineMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.LineMessage)
        codeday.squareassault.protobuf.Messages.LineMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_LineMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_LineMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codeday.squareassault.protobuf.Messages.LineMessage.class, codeday.squareassault.protobuf.Messages.LineMessage.Builder.class);
      }

      // Construct using codeday.squareassault.protobuf.Messages.LineMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_LineMessage_descriptor;
      }

      public codeday.squareassault.protobuf.Messages.LineMessage getDefaultInstanceForType() {
        return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
      }

      public codeday.squareassault.protobuf.Messages.LineMessage build() {
        codeday.squareassault.protobuf.Messages.LineMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public codeday.squareassault.protobuf.Messages.LineMessage buildPartial() {
        codeday.squareassault.protobuf.Messages.LineMessage result = new codeday.squareassault.protobuf.Messages.LineMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codeday.squareassault.protobuf.Messages.LineMessage) {
          return mergeFrom((codeday.squareassault.protobuf.Messages.LineMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codeday.squareassault.protobuf.Messages.LineMessage other) {
        if (other == codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        codeday.squareassault.protobuf.Messages.LineMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (codeday.squareassault.protobuf.Messages.LineMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.LineMessage)
    }

    static {
      defaultInstance = new LineMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.LineMessage)
  }

  public interface EchoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.EchoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>required string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code tutorial.EchoMessage}
   */
  public static final class EchoMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.EchoMessage)
      EchoMessageOrBuilder {
    // Use EchoMessage.newBuilder() to construct.
    private EchoMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EchoMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EchoMessage defaultInstance;
    public static EchoMessage getDefaultInstance() {
      return defaultInstance;
    }

    public EchoMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EchoMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              text_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_EchoMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_EchoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codeday.squareassault.protobuf.Messages.EchoMessage.class, codeday.squareassault.protobuf.Messages.EchoMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<EchoMessage> PARSER =
        new com.google.protobuf.AbstractParser<EchoMessage>() {
      public EchoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EchoMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>required string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.EchoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(codeday.squareassault.protobuf.Messages.EchoMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.EchoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.EchoMessage)
        codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_EchoMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_EchoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codeday.squareassault.protobuf.Messages.EchoMessage.class, codeday.squareassault.protobuf.Messages.EchoMessage.Builder.class);
      }

      // Construct using codeday.squareassault.protobuf.Messages.EchoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_EchoMessage_descriptor;
      }

      public codeday.squareassault.protobuf.Messages.EchoMessage getDefaultInstanceForType() {
        return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
      }

      public codeday.squareassault.protobuf.Messages.EchoMessage build() {
        codeday.squareassault.protobuf.Messages.EchoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public codeday.squareassault.protobuf.Messages.EchoMessage buildPartial() {
        codeday.squareassault.protobuf.Messages.EchoMessage result = new codeday.squareassault.protobuf.Messages.EchoMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codeday.squareassault.protobuf.Messages.EchoMessage) {
          return mergeFrom((codeday.squareassault.protobuf.Messages.EchoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codeday.squareassault.protobuf.Messages.EchoMessage other) {
        if (other == codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasText()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        codeday.squareassault.protobuf.Messages.EchoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (codeday.squareassault.protobuf.Messages.EchoMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            text_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>required string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.EchoMessage)
    }

    static {
      defaultInstance = new EchoMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.EchoMessage)
  }

  public interface ToClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ToClient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    boolean hasLine();
    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    codeday.squareassault.protobuf.Messages.LineMessage getLine();
    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    codeday.squareassault.protobuf.Messages.LineMessageOrBuilder getLineOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.ToClient}
   */
  public static final class ToClient extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.ToClient)
      ToClientOrBuilder {
    // Use ToClient.newBuilder() to construct.
    private ToClient(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ToClient(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ToClient defaultInstance;
    public static ToClient getDefaultInstance() {
      return defaultInstance;
    }

    public ToClient getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ToClient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              codeday.squareassault.protobuf.Messages.LineMessage.Builder subBuilder = null;
              if (messageCase_ == 1) {
                subBuilder = ((codeday.squareassault.protobuf.Messages.LineMessage) message_).toBuilder();
              }
              message_ = input.readMessage(codeday.squareassault.protobuf.Messages.LineMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((codeday.squareassault.protobuf.Messages.LineMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToClient_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToClient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codeday.squareassault.protobuf.Messages.ToClient.class, codeday.squareassault.protobuf.Messages.ToClient.Builder.class);
    }

    public static com.google.protobuf.Parser<ToClient> PARSER =
        new com.google.protobuf.AbstractParser<ToClient>() {
      public ToClient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToClient(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ToClient> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      LINE(1),
      MESSAGE_NOT_SET(0);
      private int value = 0;
      private MessageCase(int value) {
        this.value = value;
      }
      public static MessageCase valueOf(int value) {
        switch (value) {
          case 1: return LINE;
          case 0: return MESSAGE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.valueOf(
          messageCase_);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    public boolean hasLine() {
      return messageCase_ == 1;
    }
    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    public codeday.squareassault.protobuf.Messages.LineMessage getLine() {
      if (messageCase_ == 1) {
         return (codeday.squareassault.protobuf.Messages.LineMessage) message_;
      }
      return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
    }
    /**
     * <code>optional .tutorial.LineMessage line = 1;</code>
     */
    public codeday.squareassault.protobuf.Messages.LineMessageOrBuilder getLineOrBuilder() {
      if (messageCase_ == 1) {
         return (codeday.squareassault.protobuf.Messages.LineMessage) message_;
      }
      return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasLine()) {
        if (!getLine().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (messageCase_ == 1) {
        output.writeMessage(1, (codeday.squareassault.protobuf.Messages.LineMessage) message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (codeday.squareassault.protobuf.Messages.LineMessage) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToClient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(codeday.squareassault.protobuf.Messages.ToClient prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ToClient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ToClient)
        codeday.squareassault.protobuf.Messages.ToClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToClient_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToClient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codeday.squareassault.protobuf.Messages.ToClient.class, codeday.squareassault.protobuf.Messages.ToClient.Builder.class);
      }

      // Construct using codeday.squareassault.protobuf.Messages.ToClient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToClient_descriptor;
      }

      public codeday.squareassault.protobuf.Messages.ToClient getDefaultInstanceForType() {
        return codeday.squareassault.protobuf.Messages.ToClient.getDefaultInstance();
      }

      public codeday.squareassault.protobuf.Messages.ToClient build() {
        codeday.squareassault.protobuf.Messages.ToClient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public codeday.squareassault.protobuf.Messages.ToClient buildPartial() {
        codeday.squareassault.protobuf.Messages.ToClient result = new codeday.squareassault.protobuf.Messages.ToClient(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messageCase_ == 1) {
          if (lineBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = lineBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codeday.squareassault.protobuf.Messages.ToClient) {
          return mergeFrom((codeday.squareassault.protobuf.Messages.ToClient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codeday.squareassault.protobuf.Messages.ToClient other) {
        if (other == codeday.squareassault.protobuf.Messages.ToClient.getDefaultInstance()) return this;
        switch (other.getMessageCase()) {
          case LINE: {
            mergeLine(other.getLine());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasLine()) {
          if (!getLine().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        codeday.squareassault.protobuf.Messages.ToClient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (codeday.squareassault.protobuf.Messages.ToClient) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.valueOf(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          codeday.squareassault.protobuf.Messages.LineMessage, codeday.squareassault.protobuf.Messages.LineMessage.Builder, codeday.squareassault.protobuf.Messages.LineMessageOrBuilder> lineBuilder_;
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public boolean hasLine() {
        return messageCase_ == 1;
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.LineMessage getLine() {
        if (lineBuilder_ == null) {
          if (messageCase_ == 1) {
            return (codeday.squareassault.protobuf.Messages.LineMessage) message_;
          }
          return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 1) {
            return lineBuilder_.getMessage();
          }
          return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public Builder setLine(codeday.squareassault.protobuf.Messages.LineMessage value) {
        if (lineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          lineBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public Builder setLine(
          codeday.squareassault.protobuf.Messages.LineMessage.Builder builderForValue) {
        if (lineBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          lineBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public Builder mergeLine(codeday.squareassault.protobuf.Messages.LineMessage value) {
        if (lineBuilder_ == null) {
          if (messageCase_ == 1 &&
              message_ != codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance()) {
            message_ = codeday.squareassault.protobuf.Messages.LineMessage.newBuilder((codeday.squareassault.protobuf.Messages.LineMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 1) {
            lineBuilder_.mergeFrom(value);
          }
          lineBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public Builder clearLine() {
        if (lineBuilder_ == null) {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
          }
          lineBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.LineMessage.Builder getLineBuilder() {
        return getLineFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.LineMessageOrBuilder getLineOrBuilder() {
        if ((messageCase_ == 1) && (lineBuilder_ != null)) {
          return lineBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 1) {
            return (codeday.squareassault.protobuf.Messages.LineMessage) message_;
          }
          return codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.LineMessage line = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          codeday.squareassault.protobuf.Messages.LineMessage, codeday.squareassault.protobuf.Messages.LineMessage.Builder, codeday.squareassault.protobuf.Messages.LineMessageOrBuilder> 
          getLineFieldBuilder() {
        if (lineBuilder_ == null) {
          if (!(messageCase_ == 1)) {
            message_ = codeday.squareassault.protobuf.Messages.LineMessage.getDefaultInstance();
          }
          lineBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              codeday.squareassault.protobuf.Messages.LineMessage, codeday.squareassault.protobuf.Messages.LineMessage.Builder, codeday.squareassault.protobuf.Messages.LineMessageOrBuilder>(
                  (codeday.squareassault.protobuf.Messages.LineMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 1;
        return lineBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.ToClient)
    }

    static {
      defaultInstance = new ToClient(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.ToClient)
  }

  public interface ToServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.ToServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    boolean hasEcho();
    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    codeday.squareassault.protobuf.Messages.EchoMessage getEcho();
    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder getEchoOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.ToServer}
   */
  public static final class ToServer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tutorial.ToServer)
      ToServerOrBuilder {
    // Use ToServer.newBuilder() to construct.
    private ToServer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ToServer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ToServer defaultInstance;
    public static ToServer getDefaultInstance() {
      return defaultInstance;
    }

    public ToServer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ToServer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              codeday.squareassault.protobuf.Messages.EchoMessage.Builder subBuilder = null;
              if (messageCase_ == 1) {
                subBuilder = ((codeday.squareassault.protobuf.Messages.EchoMessage) message_).toBuilder();
              }
              message_ = input.readMessage(codeday.squareassault.protobuf.Messages.EchoMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((codeday.squareassault.protobuf.Messages.EchoMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 1;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToServer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              codeday.squareassault.protobuf.Messages.ToServer.class, codeday.squareassault.protobuf.Messages.ToServer.Builder.class);
    }

    public static com.google.protobuf.Parser<ToServer> PARSER =
        new com.google.protobuf.AbstractParser<ToServer>() {
      public ToServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToServer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ToServer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite {
      ECHO(1),
      MESSAGE_NOT_SET(0);
      private int value = 0;
      private MessageCase(int value) {
        this.value = value;
      }
      public static MessageCase valueOf(int value) {
        switch (value) {
          case 1: return ECHO;
          case 0: return MESSAGE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.valueOf(
          messageCase_);
    }

    public static final int ECHO_FIELD_NUMBER = 1;
    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    public boolean hasEcho() {
      return messageCase_ == 1;
    }
    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    public codeday.squareassault.protobuf.Messages.EchoMessage getEcho() {
      if (messageCase_ == 1) {
         return (codeday.squareassault.protobuf.Messages.EchoMessage) message_;
      }
      return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
    }
    /**
     * <code>optional .tutorial.EchoMessage echo = 1;</code>
     */
    public codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder getEchoOrBuilder() {
      if (messageCase_ == 1) {
         return (codeday.squareassault.protobuf.Messages.EchoMessage) message_;
      }
      return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasEcho()) {
        if (!getEcho().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (messageCase_ == 1) {
        output.writeMessage(1, (codeday.squareassault.protobuf.Messages.EchoMessage) message_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (codeday.squareassault.protobuf.Messages.EchoMessage) message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static codeday.squareassault.protobuf.Messages.ToServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(codeday.squareassault.protobuf.Messages.ToServer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.ToServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.ToServer)
        codeday.squareassault.protobuf.Messages.ToServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToServer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                codeday.squareassault.protobuf.Messages.ToServer.class, codeday.squareassault.protobuf.Messages.ToServer.Builder.class);
      }

      // Construct using codeday.squareassault.protobuf.Messages.ToServer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageCase_ = 0;
        message_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return codeday.squareassault.protobuf.Messages.internal_static_tutorial_ToServer_descriptor;
      }

      public codeday.squareassault.protobuf.Messages.ToServer getDefaultInstanceForType() {
        return codeday.squareassault.protobuf.Messages.ToServer.getDefaultInstance();
      }

      public codeday.squareassault.protobuf.Messages.ToServer build() {
        codeday.squareassault.protobuf.Messages.ToServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public codeday.squareassault.protobuf.Messages.ToServer buildPartial() {
        codeday.squareassault.protobuf.Messages.ToServer result = new codeday.squareassault.protobuf.Messages.ToServer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messageCase_ == 1) {
          if (echoBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = echoBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof codeday.squareassault.protobuf.Messages.ToServer) {
          return mergeFrom((codeday.squareassault.protobuf.Messages.ToServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(codeday.squareassault.protobuf.Messages.ToServer other) {
        if (other == codeday.squareassault.protobuf.Messages.ToServer.getDefaultInstance()) return this;
        switch (other.getMessageCase()) {
          case ECHO: {
            mergeEcho(other.getEcho());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasEcho()) {
          if (!getEcho().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        codeday.squareassault.protobuf.Messages.ToServer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (codeday.squareassault.protobuf.Messages.ToServer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.valueOf(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          codeday.squareassault.protobuf.Messages.EchoMessage, codeday.squareassault.protobuf.Messages.EchoMessage.Builder, codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder> echoBuilder_;
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public boolean hasEcho() {
        return messageCase_ == 1;
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.EchoMessage getEcho() {
        if (echoBuilder_ == null) {
          if (messageCase_ == 1) {
            return (codeday.squareassault.protobuf.Messages.EchoMessage) message_;
          }
          return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 1) {
            return echoBuilder_.getMessage();
          }
          return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public Builder setEcho(codeday.squareassault.protobuf.Messages.EchoMessage value) {
        if (echoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          echoBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public Builder setEcho(
          codeday.squareassault.protobuf.Messages.EchoMessage.Builder builderForValue) {
        if (echoBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          echoBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public Builder mergeEcho(codeday.squareassault.protobuf.Messages.EchoMessage value) {
        if (echoBuilder_ == null) {
          if (messageCase_ == 1 &&
              message_ != codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance()) {
            message_ = codeday.squareassault.protobuf.Messages.EchoMessage.newBuilder((codeday.squareassault.protobuf.Messages.EchoMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 1) {
            echoBuilder_.mergeFrom(value);
          }
          echoBuilder_.setMessage(value);
        }
        messageCase_ = 1;
        return this;
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public Builder clearEcho() {
        if (echoBuilder_ == null) {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 1) {
            messageCase_ = 0;
            message_ = null;
          }
          echoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.EchoMessage.Builder getEchoBuilder() {
        return getEchoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      public codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder getEchoOrBuilder() {
        if ((messageCase_ == 1) && (echoBuilder_ != null)) {
          return echoBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 1) {
            return (codeday.squareassault.protobuf.Messages.EchoMessage) message_;
          }
          return codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .tutorial.EchoMessage echo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          codeday.squareassault.protobuf.Messages.EchoMessage, codeday.squareassault.protobuf.Messages.EchoMessage.Builder, codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder> 
          getEchoFieldBuilder() {
        if (echoBuilder_ == null) {
          if (!(messageCase_ == 1)) {
            message_ = codeday.squareassault.protobuf.Messages.EchoMessage.getDefaultInstance();
          }
          echoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              codeday.squareassault.protobuf.Messages.EchoMessage, codeday.squareassault.protobuf.Messages.EchoMessage.Builder, codeday.squareassault.protobuf.Messages.EchoMessageOrBuilder>(
                  (codeday.squareassault.protobuf.Messages.EchoMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 1;
        return echoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.ToServer)
    }

    static {
      defaultInstance = new ToServer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.ToServer)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Identify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Identify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_LineMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_LineMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_EchoMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_EchoMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ToClient_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ToClient_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ToServer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ToServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)codeday/squareassault/protobuf/main.pr" +
      "oto\022\010tutorial\"\030\n\010Identify\022\014\n\004name\030\001 \002(\t\"" +
      "\033\n\013LineMessage\022\014\n\004text\030\001 \002(\t\"\033\n\013EchoMess" +
      "age\022\014\n\004text\030\001 \002(\t\"<\n\010ToClient\022%\n\004line\030\001 " +
      "\001(\0132\025.tutorial.LineMessageH\000B\t\n\007message\"" +
      "<\n\010ToServer\022%\n\004echo\030\001 \001(\0132\025.tutorial.Ech" +
      "oMessageH\000B\t\n\007messageB*\n\036codeday.squarea" +
      "ssault.protobufB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Identify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Identify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_Identify_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_tutorial_LineMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_LineMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_LineMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_tutorial_EchoMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_EchoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_EchoMessage_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_tutorial_ToClient_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tutorial_ToClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_ToClient_descriptor,
        new java.lang.String[] { "Line", "Message", });
    internal_static_tutorial_ToServer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tutorial_ToServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tutorial_ToServer_descriptor,
        new java.lang.String[] { "Echo", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
